name: anly503
channels:
  - conda-forge
dependencies:
  - python=3.9.9
  - pip=21.3.1
  - pandas=1.3.5
  - dask=2022.1.0
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - pillow=8.4.0
  - plotly=5.5.0
  - altair=4.2.0
  - bokeh=2.4.2
  - scikit-learn=1.0.2
  - networkx=2.6.3
  - holoviews=1.14.7
  - datashader=0.13.0
  - igraph=0.9.6
  - geopandas=0.10.2
  - openpyxl=3.0.9
  - pathlib=1.0.1
  - pyarrow=6.0.1
  - pyreadr=0.4.4
  - umap-learn=0.5.2
  - yellowbrick=1.3.post1
  - hvplot=0.7.3
  - fastparquet=0.8.0
  - pip:
    - rdatasets==0.1.0
    - wbdata==0.3.0
